-- 코드를 입력하세요
SELECT CC.CAR_ID, CC.CAR_TYPE, ROUND(CC.DAILY_FEE * (100 - CP.DISCOUNT_RATE) * 30 / 100, 0) FEE
FROM CAR_RENTAL_COMPANY_CAR CC, CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
WHERE CC.CAR_TYPE = CP.CAR_TYPE
    AND (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
    AND CP.DURATION_TYPE = '30일 이상'
    AND CC.CAR_ID NOT IN (SELECT CAR_ID
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
                         WHERE START_DATE < '2022-12-01' AND END_DATE >= '2022-11-01')
GROUP BY CC.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000