-- 코드를 입력하세요
SELECT UU.USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) '전체주소', CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) '전화번호'
FROM USED_GOODS_BOARD UB
INNER JOIN USED_GOODS_USER UU
ON UB.WRITER_ID = UU.USER_ID
GROUP BY UB.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY UU.USER_ID DESC