-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, 
       MONTH(SALES_DATE) MONTH,
       GENDER,
       COUNT(DISTINCT USER_INFO.USER_ID) AS 'USERS'
FROM USER_INFO, ONLINE_SALE
WHERE USER_INFO.USER_ID = ONLINE_SALE.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER