-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE < '2022-06-01'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID
