-- 코드를 입력하세요
SELECT TITLE, UB.BOARD_ID, REPLY_ID, UR.WRITER_ID, UR.CONTENTS, DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD UB, USED_GOODS_REPLY UR
WHERE UB.BOARD_ID = UR.BOARD_ID AND UB.CREATED_DATE >= '2022-10-01' AND UB.CREATED_DATE < '2022-11-01'
ORDER BY UR.CREATED_DATE, TITLE