-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', CONCAT(UF.FILE_ID,FILE_NAME,FILE_EXT)) FILE_PATH
FROM USED_GOODS_FILE UF
INNER JOIN USED_GOODS_BOARD UB
ON UF.BOARD_ID = UB.BOARD_ID
WHERE (UB.BOARD_ID, UB.VIEWS)  = (SELECT UB.BOARD_ID, UB.VIEWS
                    FROM USED_GOODS_BOARD UB
                    ORDER BY UB.VIEWS DESC
                    LIMIT 1)
ORDER BY UF.FILE_ID DESC